// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('HelloTestRobobar', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('1xRob(w)ine', async function() {
    // Test name: 1xRob(w)ine
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1847x935 | 
    await driver.manage().window().setRect({ width: 1847, height: 935 })
    // 3 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    // 4 | assertText | css=tr:nth-child(4) > .ng-binding | €3.00
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€3.00")
    // 5 | close |  | 
    await driver.close()
  })
  it('1xRobaCola -> Checkout', async function() {
    // Test name: 1xRobaCola -> Checkout
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1847x935 | 
    await driver.manage().window().setRect({ width: 1847, height: 935 })
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 4 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 5 | mouseOver | css=.btn-success | 
    {
      const element = await driver.findElement(By.css(".btn-success"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 6 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 7 | close |  | 
    await driver.close()
  })
  it('1xRobaCola+1xRoboBeer', async function() {
    // Test name: 1xRobaCola+1xRoboBeer
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1847x935 | 
    await driver.manage().window().setRect({ width: 1847, height: 935 })
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 4 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 5 | assertText | css=tr:nth-child(4) > .ng-binding | €3.25
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€3.25")
    // 6 | close |  | 
    await driver.close()
  })
  it('1xRobaCola+1xRoboBeer+1xRob(w)ine', async function() {
    // Test name: 1xRobaCola+1xRoboBeer+1xRob(w)ine
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1847x935 | 
    await driver.manage().window().setRect({ width: 1847, height: 935 })
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 4 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 5 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    // 6 | assertText | css=tr:nth-child(4) > .ng-binding | €6.25
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€6.25")
    // 7 | close |  | 
    await driver.close()
  })
  it('1xRoboBeer', async function() {
    // Test name: 1xRoboBeer
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1847x935 | 
    await driver.manage().window().setRect({ width: 1847, height: 935 })
    // 3 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 4 | assertText | css=tr:nth-child(4) > .ng-binding | €2.00
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€2.00")
    // 5 | close |  | 
    await driver.close()
  })
  it('1xRoboBeer -> Checkout < 18', async function() {
    // Test name: 1xRoboBeer -> Checkout < 18
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1847x935 | 
    await driver.manage().window().setRect({ width: 1847, height: 935 })
    // 3 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 4 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 5 | click | id=ageInput | 
    await driver.findElement(By.id("ageInput")).click()
    // 6 | type | id=ageInput | 17
    await driver.findElement(By.id("ageInput")).sendKeys("17")
    // 7 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 8 | assertText | css=.alert > .ng-binding | Only adults can buy alcohol!
    assert(await driver.findElement(By.css(".alert > .ng-binding")).getText() == "Only adults can buy alcohol!")
    // 9 | close |  | 
    await driver.close()
  })
  it('1xRoboBeer -> Checkout >=18', async function() {
    // Test name: 1xRoboBeer -> Checkout >=18
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1847x935 | 
    await driver.manage().window().setRect({ width: 1847, height: 935 })
    // 3 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 4 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 5 | click | id=ageInput | 
    await driver.findElement(By.id("ageInput")).click()
    // 6 | type | id=ageInput | 21
    await driver.findElement(By.id("ageInput")).sendKeys("21")
    // 7 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 8 | close |  | 
    await driver.close()
  })
  it('1xRoboCola', async function() {
    // Test name: 1xRoboCola
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1847x935 | 
    await driver.manage().window().setRect({ width: 1847, height: 935 })
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 4 | assertText | css=tr:nth-child(4) > .ng-binding | €1.25
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€1.25")
    // 5 | close |  | 
    await driver.close()
  })
  it('2xRob(w)ine', async function() {
    // Test name: 2xRob(w)ine
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1847x935 | 
    await driver.manage().window().setRect({ width: 1847, height: 935 })
    // 3 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    // 4 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    // 5 | assertText | css=tr:nth-child(4) > .ng-binding | €6.00
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€6.00")
    // 6 | close |  | 
    await driver.close()
  })
  it('2xRoboBeer', async function() {
    // Test name: 2xRoboBeer
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1847x935 | 
    await driver.manage().window().setRect({ width: 1847, height: 935 })
    // 3 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 4 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 5 | assertText | css=tr:nth-child(4) > .ng-binding | €4.00
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€4.00")
    // 6 | close |  | 
    await driver.close()
  })
  it('2xRoboCola', async function() {
    // Test name: 2xRoboCola
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1847x935 | 
    await driver.manage().window().setRect({ width: 1847, height: 935 })
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 4 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 5 | assertText | css=tr:nth-child(4) > .ng-binding | €2.50
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€2.50")
    // 6 | close |  | 
    await driver.close()
  })
})
